const optionsDescription = {
  V: 'Variable spindle enabled ',
  N: 'Line numbers enabled ',
  M: 'Mist coolant enabled ',
  C: 'CoreXY enabled ',
  P: 'Parking motion enabled ',
  Z: 'Homing force origin enabled ',
  H: 'Homing single axis enabled ',
  T: 'Two limit switches on axis enabled ',
  D: 'Spindle direction pin used as enable pin ',
  0: 'Spindle enable off when speed is zero enabled ',
  S: 'Software limit pin debouncing enabled ',
  R: 'Parking override control enabled ',
  A: 'Allow feed rate overrides in probe cycles ',
  '+': 'Safety door input pin enabled ',
  '*': 'Restore all EEPROM disabled ',
  $: 'Restore EEPROM `$` settings disabled ',
  '#': 'Restore EEPROM parameter data disabled ',
  I: 'Build info write user string disabled ',
  E: 'Force sync upon EEPROM write disabled ',
  W: 'Force sync upon work coordinate offset change disabled ',
  L: 'Homing initialization auto-lock disabled ',
};
